# Site settings
author: Melissa Williams
title: Melissa Williams
header-img: img/home-bg.png
email: melissa@brandmeetscopy.com
copyright_name: Melissa Williams
description: > # this means to ignore newlines until "baseurl:"
  My journey through Flatiron's Software Engineering program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  meliew

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
